---
title: "Stochastic Models"
author: "Sarthak"
date: "2/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

setwd("C:/Users/Admin/Desktop/Project1")
#.libPaths('C:/Users/Admin/Documents/R/win-library/4.1')

library(reticulate)
use_python("C:/Users/Admin/Anaconda3/python.exe")
#use_python("C:/Users/Admin/AppData/Local/Programs/Python/Python36/python.exe")
```

## R Markdown

```{r, include=F}
library(janitor)
library(pacman)
library(tidyverse)
library(listenv)
library(magrittr)
```

```{python, include=F}
import os
import sys
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

import gc
from statsmodels.tsa.stattools import adfuller, kpss
from arch.unitroot import ADF, PhillipsPerron, ZivotAndrews, KPSS, engle_granger
from statsmodels.tsa.vector_ar.vecm import coint_johansen

from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from pmdarima.arima.utils import ndiffs
```

```{python}
t = 10 
s = 5
NoOfPaths=100
NoOfSteps=10

#E(W(t)|W(0)) = W(0)=0
def martingaleA():
    W_t = np.random.normal(0.0,t**0.5,[NoOfPaths,1])
    E_W_t = np.mean(W_t)
    print("Simuated mean={}, expected mean={}".format(E_W_t,0.0))
martingaleA()
  
#E(W(t)|W(s)) = W(s)
def martingaleB():    
    Z = np.random.normal(0.0,1.0,[NoOfPaths,NoOfSteps])
    W = np.zeros([NoOfPaths,NoOfSteps+1])
        
    # time-step from [0,s]
    dt1 = s / float(NoOfSteps)
    for i in range(0,NoOfSteps):
        # making sure that samples from normal have mean 0 and variance 1
        Z[:,i] = (Z[:,i] - np.mean(Z[:,i])) / np.std(Z[:,i])
        W[:,i+1] = W[:,i] + pow(dt1,0.5)*Z[:,i]
            
    #W_s is the last column of W
    W_s = W[:,-1]
    #for every path W(s) we perform sub-simulation until time t and calculate
    #the expectation
    # time-step from [s,t]
    dt2     = (t-s)/float(NoOfSteps);
    W_t     = np.zeros([NoOfPaths,NoOfSteps+1]);
    
    #Store the results
    E_W_t = np.zeros([NoOfPaths])
    Error=[]
    for i in range(0,NoOfPaths):
        #Sub-simulation from time "s" until "t"
        W_t[:,0] = W_s[i];
        Z = np.random.normal(0.0,1.0,[NoOfPaths,NoOfSteps])
        for j in range(0,NoOfSteps):
            #this is a scaling that ensures that Z has mean 0 and variance 1
            Z[:,j] = (Z[:,j]-np.mean(Z[:,j])) / np.std(Z[:,j]);
            #path simulation, from "s" until "t"
            W_t[:,j+1] = W_t[:,j] + pow(dt2,0.5)*Z[:,j];        
            
        E_W_t[i]=np.mean(W_t[:,-1])
        Error.append(E_W_t[i]-W_s[i])
        
        #Generate a plot for the first path
        if i==0:
            plt.plot(np.linspace(0,s,NoOfSteps+1),W[0,:])
            for j in range(0,NoOfPaths):
                plt.plot(np.linspace(s,t,NoOfSteps+1),W_t[j,:])
            plt.xlabel("time")
            plt.ylabel("W(t)")
            plt.grid()
            plt.show()
        
    print(Error)
    error = np.max(np.abs(E_W_t-W_s))
    print("The error = {}".format(error))
    
martingaleB()
```

